### ISSUE TITLE
로그인/비로그인 사용자 헤더 변환 및 layout 적용

### ISSUE THREAD

**Issue by kkh-147-17-3** [Z-P0P/ZPOP#12]
- [x] 사용자/비로그인 사용자 헤더 변환
- [x] thymeleaf layout-dialect 를 이용한 헤더 레이아웃 적용

확인필요사항
1.  component 폴더명
2. 레이아웃 구조
3. 폴더구조

**Comment by a-ryang** [comment]
task 완료되었는데 이슈 닫을까요??

**Comment by kkh-147-17-3** [comment]
제가 닫을게요
