### ISSUE TITLE
defaultMemberService에서 데이터를 가공하는 과정중에 발생한 문제

### ISSUE THREAD

**Issue by Hell0Stranger** [Z-P0P/ZPOP#34]
myMeetingView를 바탕으로하여 화면에 가공된 데이터를 보여주려고 하는 과정에 문제를 만났습니다.
myMeetingView에 존재하는 DATE startedAt과 int genderCategory를  MyMeetingResponse 타입의 새 객체에서 각각 String으로 가공하려고 하는과정중에 list에 값이 담기지 않는 현상이 발생합니다 😥 생성자는 올바르게 추가한 것같은데 같이 고민해주시면 감사하겠습니다.

**Comment by kkh-147-17-3** [comment]
값이 어떻게 담기지 않는 것인지 혹시 결과 화면을 보여주실 수 있나요?

**Comment by Hell0Stranger** [comment]
![image](https://user-images.githubusercontent.com/112043767/209498102-dc6c5a1a-e0fb-491e-bc6d-66e4f41ef520.png)
미팅뷰에서는 잘 가져오는데 
미팅리스폰스는 null로 담겨지네용 ㅠㅠ

**Comment by Hell0Stranger** [comment]
mysql의 tiny int 는 java에서 boolean으로 받아주어야합니다 ^-^..
