### ISSUE TITLE
소셜 로그인 관련 이슈

### ISSUE THREAD

**Issue by kkh-147-17-3** [Z-P0P/ZPOP#9]
1. 카카오 로그인은 괜찮으나 네아로(네이버아이디로그인) 의 경우 앱 심사 없이 개발자 계정으로 등록한 상태에서는 해당 개발자 계정으로만 로그인된다고 합니다.

2. 사용자가 소셜 로그인을 로그아웃해서 다른 계정으로 들어가고 싶은 경우가 있을텐데, 그 부분은 논의 필요합니다.
=> 예를 들면 'ABC'라는 컴퓨터에서 'A'라는 카카오 계정으로 로그인했을 때, 이후에 'B'라는 카카오 계정으로 로그인하는 경우가 있을 수 있을 것 같습니다.

3. access토큰 및 사용자 프로필을 response로 받을 때 사용되는 객체를 com.zpop.web.service에 넣을지 아니면 다른 곳에 넣을 지 고민됩니다. entity는 아닌 것 같아서 service에 넣었어요.

**Comment by kkh-147-17-3** [comment]
1. 의 경우 test ID 를 계정에 추가하면 된다고 합니다. 이후에 zpop 의 소셜 로그인 api 계정 확정되면 그 계정에 추가하면 될 것 같습니다.

**Comment by a-ryang** [comment]
2번이 잘 와닿지 않는데,
카카오 로그인 버튼을 누르면 카카오쪽 세션이 남아서 바로 로그인 되버리는 문제죠??

**Comment by kkh-147-17-3** [comment]
> 2번이 잘 와닿지 않는데, 카카오 로그인 버튼을 누르면 카카오쪽 세션이 남아서 바로 로그인 되버리는 문제죠??

이전에 네이버 로그인을 한 상태에서 네이버로그인 버튼을 누르면 네이버 로그인 화면이 나오지 않고 자동으로 토큰 가져오는거까지 넘어가는거요

**Comment by kkh-147-17-3** [comment]
간악한 네이버 네아로 api 설명이 예전버전이고 불충분했음
네이버의 js 쓰는거보다 직접 js 만들어서 사용
